deployment:
  tasks:
    - export DEPLOY_PATH=/home/example/public_html/
    - echo "Deploying to $DEPLOY_PATH"
    - /bin/rm -rf $DEPLOY_PATH/*
    - /bin/cp -R * $DEPLOY_PATH/
    - echo "Deployment complete."
